### ISSUE TITLE
PreviewTime not optional

### ISSUE THREAD

**Issue by de-odex** [llllllllll/slider#18]
```
Traceback (most recent call last):
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\library.py", line 243, in lookup_by_id
    return self._read_beatmap(self, beatmap_id=beatmap_id)
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\library.py", line 216, in _raw_read_beatmap
    return Beatmap.from_path(self._cache[f'id:{beatmap_id}'])
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\library.py", line 32, in __getitem__
    return d[key]
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\dbm\dumb.py", line 148, in __getitem__
    pos, siz = self._index[key]     # may raise KeyError
KeyError: b'id:75'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\beatmap.py", line 767, in _get_as_str
    return mapping[field]
KeyError: 'PreviewTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 180, in sendpp
    beatmap_data = osu_library.lookup_by_id(beatmap_id, download=True, save=True)
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\library.py", line 247, in lookup_by_id
    return self.download(beatmap_id, save=save)
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\library.py", line 360, in download
    beatmap = Beatmap.parse(data.decode('utf-8-sig'))
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\beatmap.py", line 1611, in parse
    milliseconds=_get_as_int(groups, 'General', 'PreviewTime'),
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\beatmap.py", line 794, in _get_as_int
    v = _get_as_str(groups, section, field, default)
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\beatmap.py", line 770, in _get_as_str
    raise ValueError(f'missing field {field!r} in section {section!r}')
ValueError: missing field 'PreviewTime' in section 'General'
```
on https://osu.ppy.sh/b/75

**Comment by tybug** [comment]
closed by https://github.com/llllllllll/slider/pull/87
