### ISSUE TITLE
I get a syntax error upon importing slider

### ISSUE THREAD

**Issue by jamesguessis** [llllllllll/slider#23]
```python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import slider
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jamu/.local/lib/python3.5/site-packages/slider/__init__.py", line 1, in <module>
    from .beatmap import Beatmap
  File "/home/jamu/.local/lib/python3.5/site-packages/slider/beatmap.py", line 63
    f'volume must be in the range [0, 100], got {volume!r}',
                                                          ^
SyntaxError: invalid syntax```

**Comment by llllllllll** [comment]
Slider requires Python 3.6, which is the first version that introduces `f-string`s

**Comment by jamesguessis** [comment]
ah, not to nag you should probably put that in the readme somewhere :+1:

**Comment by llllllllll** [comment]
I have it in the setup.py trove classifiers, but I agree that the readme is a more visible place for that. I can put it in a dependencies section. Thanks!
