### ISSUE TITLE
some odd error with user_id and user_name in client.user()

### ISSUE THREAD

**Issue by de-odex** [llllllllll/slider#28]
```
Traceback (most recent call last):
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\deodex\Documents\DiscordBot2\commands\osu.py", line 67, in sendosu
    await self.osu_logic(ctx.message.server.get_member(user_id))
  File "C:\Users\deodex\Documents\DiscordBot2\commands\osu.py", line 54, in osu_logic
    user = self.osu_api_client.user(user_id=int(osu_user_id))
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\client.py", line 766, in user
    for k, v in dict_.items()
  File "C:\Users\deodex\AppData\Local\Programs\Python\Python36\lib\site-packages\slider\client.py", line 767, in <dictcomp>
    if k in self._user_conversions
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by llllllllll** [comment]
is this all ids or just one?

**Comment by de-odex** [comment]
holy shoot sorry for ultra late comment
no idea anymore; shoot

**Comment by de-odex** [comment]
Now that i think about it, this most likely was because of my error, not from the library
