### ISSUE TITLE
loved beatmap fails to parse

### ISSUE THREAD

**Issue by tybug** [llllllllll/slider#71]
doing

```python
from slider import *
library = Library(".")
library.lookup_by_id(1746902, download=True)
``` 

throws

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/library.py", line 256, in lookup_by_id
    return self._read_beatmap(self, beatmap_id=beatmap_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/library.py", line 224, in _raw_read_beatmap
    raise KeyError(key)
KeyError: 1746902

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/beatmap.py", line 154, in parse
    offset, ms_per_beat, *rest = data.split(',')
ValueError: not enough values to unpack (expected at least 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tybug/Desktop/coding/sandbox/__circleguard.py", line 7, in <module>
    library.lookup_by_id(1746902, download=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/library.py", line 260, in lookup_by_id
    return self.download(beatmap_id, save=save)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/library.py", line 384, in download
    beatmap = Beatmap.parse(data.decode('utf-8-sig'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/beatmap.py", line 1901, in parse
    timing_point = TimingPoint.parse(raw_timing_point, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/slider/beatmap.py", line 157, in parse
    f'failed to parse {cls.__qualname__} from {data!r}',
ValueError: failed to parse TimingPoint from ' '
```

I'm guessing this is because there are multiple newlines between the sections in this particular beatmap, but I haven't investigated much beyond that.

link: https://osu.ppy.sh/beatmapsets/833927#osu/1746902

**Comment by tybug** [comment]
I was mistaken - the issue here is that some lines have additional whitespace when they should be empty.
