### ISSUE TITLE
Old beatmaps (file format v3) fail to parse

### ISSUE THREAD

**Issue by tybug** [llllllllll/slider#79]
```python
from slider import *
library = Library(".")
beatmap = library.lookup_by_id(177, download=True)
```

fails with 
```python
Traceback (most recent call last):
  File "/Users/tybug/Desktop/coding/osu/slider/slider/library.py", line 256, in lookup_by_id
    return self._read_beatmap(self, beatmap_id=beatmap_id)
  File "/Users/tybug/Desktop/coding/osu/slider/slider/library.py", line 224, in _raw_read_beatmap
    raise KeyError(key)
KeyError: 177

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tybug/Desktop/coding/osu/slider/slider/beatmap.py", line 757, in _get_as_str
    return mapping[field]
KeyError: 'PreviewTime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tybug/Desktop/coding/sandbox/__circleguard.py", line 10, in <module>
    beatmap = library.lookup_by_id(177, download=True)
  File "/Users/tybug/Desktop/coding/osu/slider/slider/library.py", line 260, in lookup_by_id
    return self.download(beatmap_id, save=save)
  File "/Users/tybug/Desktop/coding/osu/slider/slider/library.py", line 408, in download
    beatmap = Beatmap.parse(data.decode('utf-8-sig'))
  File "/Users/tybug/Desktop/coding/osu/slider/slider/beatmap.py", line 1936, in parse
    milliseconds=_get_as_int(groups, 'General', 'PreviewTime'),
  File "/Users/tybug/Desktop/coding/osu/slider/slider/beatmap.py", line 784, in _get_as_int
    v = _get_as_str(groups, section, field, default)
  File "/Users/tybug/Desktop/coding/osu/slider/slider/beatmap.py", line 760, in _get_as_str
    raise ValueError(f'missing field {field!r} in section {section!r}')
ValueError: missing field 'PreviewTime' in section 'General'
```

My guess is all beatmaps of this version or earlier will fail, and potentially later versions as well (I don't know when PreviewTime was added). Slider should conditionally parse based on version. 

There are probably other attributes missing in various old format versions, but I can't find a spec for anything other than v14 (the latest version) on the wiki.

**Comment by jxu** [comment]
or just leave it missing

**Comment by tybug** [comment]
I'm fine with that resolution, but that means making some Beatmap fields nullable, which might allow invalid .osu files to be parsed as valid ones. For instance, a v14 beatmap that is missing fields which v14 requires would be parsed fine under this approach, just with missing fields being `None`. 

Alternatively, we could fill missing fields with their default value. It looks like most fields have a default value listed on [the wiki](https://osu.ppy.sh/wiki/en/osu%21_File_Formats/Osu_%28file_format%29), and the one's that don't we can probably come up with a reasonable default. This runs into the same problem above as accepting otherwise invalid osu files, but I don't see a way around that without knowing the details of each osu version.

**Comment by jxu** [comment]
yeah you could have it parse with a warning if the detected version is
below 14. idk the versioning either.
